# Generated by Django 3.0.5 on 2020-05-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200506_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedico',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermedico',
            name='tipo_usuario',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
