# Generated by Django 3.0.5 on 2020-04-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion_Medica',
            fields=[
                ('id_atencion_medica', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_atencion_medica', models.DateField()),
                ('nombre_medico', models.CharField(max_length=255)),
                ('fecha_prox_atencion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Atención Medica',
                'verbose_name_plural': 'Atenciones Medicas',
                'db_table': 'atencion_medica',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega_medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField()),
                ('fecha_proxima_entrega', models.DateField(blank=True, null=True)),
                ('nombre_farmaceutico', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id_error', models.IntegerField(primary_key=True, serialize=False)),
                ('nro_error', models.IntegerField()),
                ('codigo_error', models.CharField(max_length=255)),
                ('fecha_hora_error', models.DateField()),
                ('lugar_error', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Errores',
                'db_table': 'error',
            },
        ),
        migrations.CreateModel(
            name='Estado_Reserva',
            fields=[
                ('id_estado_reserva', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo_estado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado Reserva',
                'verbose_name_plural': 'Estado Reservas',
                'db_table': 'estado_reserva',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=255)),
                ('formato', models.CharField(max_length=255)),
                ('gr_ml', models.CharField(max_length=255)),
                ('laboratorio', models.CharField(max_length=255)),
                ('total_disponible', models.IntegerField()),
                ('total_reservado', models.IntegerField(blank=True, null=True)),
                ('total_retirado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ap_paterno', models.CharField(max_length=255)),
                ('ap_materno', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('nro_celular', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('nombre_familiar', models.CharField(max_length=255)),
                ('nro_familiar', models.CharField(max_length=255)),
                ('email_familiar', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Informe',
            fields=[
                ('id_tipo_informe', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_informe', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo Informe',
                'verbose_name_plural': 'Tipo Informes',
                'db_table': 'tipo_informe',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(max_length=255)),
                ('nivel_usuario', models.IntegerField()),
                ('nombre_completo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_reservada', models.IntegerField()),
                ('fecha_reserva', models.DateField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('id_estado_reserva', models.ForeignKey(db_column='id_estado_reserva', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Estado_Reserva')),
                ('id_medicamento_recetado', models.ForeignKey(db_column='id_medicamento_recetado', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Reposicion',
            fields=[
                ('id_reposicion', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_repuesta', models.FloatField()),
                ('fecha_reposicion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('nombre_farmaceutico', models.CharField(max_length=255)),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento')),
            ],
            options={
                'verbose_name': 'Reposición',
                'verbose_name_plural': 'Repocisiones',
                'db_table': 'reposicion',
            },
        ),
        migrations.CreateModel(
            name='Receta_Medica',
            fields=[
                ('id_receta', models.IntegerField(primary_key=True, serialize=False)),
                ('id_atencion_medica', models.ForeignKey(db_column='id_atencion_medica', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Atencion_Medica')),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
                'db_table': 'receta_medica',
            },
        ),
        migrations.CreateModel(
            name='Medicamento_Recetado',
            fields=[
                ('id_medicamento_recetado', models.IntegerField(primary_key=True, serialize=False)),
                ('duracion', models.CharField(max_length=255)),
                ('frecuencia', models.CharField(max_length=255)),
                ('cantidad_recetada', models.IntegerField()),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento')),
                ('id_receta_medica', models.ForeignKey(db_column='id_receta_medica', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Receta_Medica')),
            ],
            options={
                'verbose_name': 'Medicamento Recetado',
                'verbose_name_plural': 'Medicamentos Recetados',
                'db_table': 'medicamento_recetado',
            },
        ),
        migrations.CreateModel(
            name='Medicamento_Entregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.IntegerField()),
                ('id_entrega_medicamento', models.ForeignKey(db_column='id_entrega_medicamento', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Entrega')),
                ('id_medicamento_recetado', models.ForeignKey(db_column='id_medicamento_recetado', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento_Recetado')),
            ],
            options={
                'verbose_name': 'Medicamento Entregado',
                'verbose_name_plural': 'Medicmentos Entregados',
                'db_table': 'medicamento_entregado',
            },
        ),
        migrations.CreateModel(
            name='Informe_Medicamento',
            fields=[
                ('id_informe', models.IntegerField(primary_key=True, serialize=False)),
                ('id_medicamento', models.IntegerField()),
                ('nombre_medicamento', models.CharField(max_length=255)),
                ('cantidad', models.CharField(max_length=255)),
                ('nombre_farmaceutico', models.CharField(max_length=255)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_tipo_informe', models.ForeignKey(db_column='id_tipo_informe', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Tipo_Informe')),
            ],
            options={
                'verbose_name': 'Informe de Medicamento',
                'verbose_name_plural': 'Informes de Medicamentos',
                'db_table': 'informe_medicamento',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Atencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.CharField(max_length=255)),
                ('diagnostico', models.CharField(max_length=255)),
                ('tratamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_atencion_medica', models.ForeignKey(db_column='id_atencion_medica', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Atencion_Medica')),
            ],
            options={
                'verbose_name': 'Detalle Atención',
                'verbose_name_plural': 'Detalle Atenciones',
                'db_table': 'detalle_atencion',
            },
        ),
        migrations.CreateModel(
            name='Carnet_Paciente',
            fields=[
                ('nro_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=255)),
                ('prevision', models.CharField(max_length=255)),
                ('grupo_sanguineo', models.CharField(max_length=255)),
                ('cesfam', models.CharField(max_length=255)),
                ('rut_paciente', models.ForeignKey(db_column='rut_paciente', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Paciente')),
            ],
            options={
                'verbose_name': 'Carnet Paciente',
                'verbose_name_plural': 'Carnet Pacientes',
                'db_table': 'carnet_paciente',
            },
        ),
        migrations.AddField(
            model_name='atencion_medica',
            name='nro_ficha',
            field=models.ForeignKey(db_column='nro_ficha', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Carnet_Paciente'),
        ),
    ]
