# Generated by Django 3.0.5 on 2020-04-19 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion_Medica',
            fields=[
                ('id_atencion_medica', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_atencion_medica', models.DateField()),
            ],
            options={
                'verbose_name': 'Atención Medica',
                'verbose_name_plural': 'Atenciones Medicas',
                'db_table': 'atencion_medica',
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id_error', models.IntegerField(primary_key=True, serialize=False)),
                ('nro_error', models.IntegerField()),
                ('codigo_error', models.CharField(max_length=255)),
                ('fecha_hora_error', models.DateField()),
                ('lugar_error', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Errores',
                'db_table': 'error',
            },
        ),
        migrations.CreateModel(
            name='Estado_Reserva',
            fields=[
                ('id_estado_reserva', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo_estado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado Reserva',
                'verbose_name_plural': 'Estado Reservas',
                'db_table': 'estado_reserva',
            },
        ),
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('rut_farmaceutico', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_farmaceutico', models.CharField(max_length=255)),
                ('ap_paterno', models.CharField(max_length=255)),
                ('ap_materno', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Farmaceutico',
                'verbose_name_plural': 'Farmaceuticos',
                'db_table': 'farmaceutico',
            },
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id_farmacia', models.IntegerField(primary_key=True, serialize=False)),
                ('nro_farmacia', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
                'db_table': 'farmacia',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=255)),
                ('formato', models.CharField(max_length=255)),
                ('gr_ml', models.CharField(max_length=255)),
                ('laboratorio', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut_medico', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('ap_paterno', models.CharField(max_length=255)),
                ('ap_materno', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ap_paterno', models.CharField(max_length=255)),
                ('ap_materno', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Receta_Medica',
            fields=[
                ('id_receta', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
                'db_table': 'receta_medica',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Retiro',
            fields=[
                ('id_tipo_retiro', models.IntegerField(primary_key=True, serialize=False)),
                ('razon_retiro', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo Retiro',
                'verbose_name_plural': 'Tipos Retiro',
                'db_table': 'tipo_retiro',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=1)),
                ('tipo_usuario', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_disponible', models.IntegerField()),
                ('cant_reservada', models.IntegerField()),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Retiro_Stock',
            fields=[
                ('id_retiro', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_retiro', models.DateField()),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento')),
                ('id_tipo_retiro', models.ForeignKey(db_column='id_tipo_retiro', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Tipo_Retiro')),
            ],
            options={
                'verbose_name': 'Retiro Stock',
                'verbose_name_plural': 'Restiros Stock',
                'db_table': 'retiro_stock',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_unitaria', models.IntegerField()),
                ('fecha_reserva', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('agregado', models.CharField(max_length=1)),
                ('descontado', models.CharField(max_length=1)),
                ('id_estado_reserva', models.ForeignKey(db_column='id_estado_reserva', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Estado_Reserva')),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Reposicion',
            fields=[
                ('id_reposicion', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_unitaria', models.IntegerField()),
                ('fecha_hora_reposicion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento')),
                ('rut_farmaceutico', models.ForeignKey(db_column='rut_farmaceutico', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Farmaceutico')),
            ],
            options={
                'verbose_name': 'Reposición',
                'verbose_name_plural': 'Repocisiones',
                'db_table': 'reposicion',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega_medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_entrega', models.DateField()),
                ('fecha_proxima_entrega', models.DateField()),
                ('id_farmacia', models.ForeignKey(db_column='id_farmacia', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Farmacia')),
                ('rut_farmaceutico', models.ForeignKey(db_column='rut_farmaceutico', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Farmaceutico')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Atencion',
            fields=[
                ('id_detalle_atencion', models.IntegerField(primary_key=True, serialize=False)),
                ('sintomas', models.CharField(max_length=255)),
                ('diagnostico', models.CharField(max_length=255)),
                ('tratamiento', models.CharField(max_length=255)),
                ('observacion', models.CharField(max_length=255)),
                ('control_medico', models.CharField(max_length=1)),
                ('id_atencion_medica', models.ForeignKey(db_column='id_atencion_medica', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Atencion_Medica')),
            ],
            options={
                'verbose_name': 'Detalle Atención',
                'verbose_name_plural': 'Detalle Atenciones',
                'db_table': 'detalle_atencion',
            },
        ),
        migrations.CreateModel(
            name='Carnet_Paciente',
            fields=[
                ('nro_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('nro_celular', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=255)),
                ('prevision', models.CharField(max_length=255)),
                ('grupo_sanguineo', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('cesfam', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=1)),
                ('rut_paciente', models.ForeignKey(db_column='rut_paciente', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Paciente')),
            ],
            options={
                'verbose_name': 'Carnet Paciente',
                'verbose_name_plural': 'Carnet Pacientes',
                'db_table': 'carnet_paciente',
            },
        ),
        migrations.AddField(
            model_name='atencion_medica',
            name='id_receta',
            field=models.ForeignKey(db_column='id_receta', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Receta_Medica'),
        ),
        migrations.AddField(
            model_name='atencion_medica',
            name='nro_ficha',
            field=models.ForeignKey(db_column='nro_ficha', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Carnet_Paciente'),
        ),
        migrations.AddField(
            model_name='atencion_medica',
            name='rut_medico',
            field=models.ForeignKey(db_column='rut_medico', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medico'),
        ),
        migrations.CreateModel(
            name='Detalle_Receta',
            fields=[
                ('id_receta', models.OneToOneField(db_column='id_receta', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Cestock.Receta_Medica')),
                ('duracion', models.CharField(max_length=255)),
                ('frecuencia', models.CharField(max_length=255)),
                ('id_entrega_medicamento', models.ForeignKey(db_column='id_entrega_medicamento', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Entrega')),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento')),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='Cestock.Reserva')),
            ],
            options={
                'verbose_name': 'Detalle Receta',
                'verbose_name_plural': 'Detalle Recetas',
                'db_table': 'detalle_receta',
            },
        ),
    ]
