# Generated by Django 3.0.5 on 2020-04-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion_medica',
            name='fecha_hora_atencion_medica',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='atencion_medica',
            name='id_atencion_medica',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='id_detalle_atencion',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
