# Generated by Django 3.0.5 on 2020-04-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carnet_paciente',
            old_name='rut_paciente',
            new_name='paciente_rut_paciente',
        ),
    ]
