# Generated by Django 3.0.5 on 2020-04-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0002_auto_20200420_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carnet_paciente',
            old_name='paciente_rut_paciente',
            new_name='rut_paciente',
        ),
    ]
