# Generated by Django 3.0.5 on 2020-04-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0004_detalle_atencion_atencion_medica'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe_medicamento',
            name='id_tipo_informe',
            field=models.ForeignKey(db_column='id_tipo_informe', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Tipo_Informe'),
        ),
    ]
