# Generated by Django 3.0.5 on 2020-05-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0016_auto_20200506_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reposicion',
            name='fecha_reposicion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reposicion',
            name='fecha_vencimiento',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
