# Generated by Django 3.0.5 on 2020-05-07 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0017_auto_20200506_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reposicion',
            name='fecha_reposicion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reposicion',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
