# Generated by Django 3.0.5 on 2020-05-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0018_auto_20200506_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id_recordatorio', models.IntegerField(primary_key=True, serialize=False)),
                ('id_medicamento', models.IntegerField(blank=True, default=0, null=True)),
                ('nombre_medicamento', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'db_table': 'recordatorio',
            },
        ),
        migrations.AlterModelOptions(
            name='tipo_retiro',
            options={'verbose_name': 'Tipo Retiro', 'verbose_name_plural': 'Tipo Retiros'},
        ),
        migrations.AddField(
            model_name='error',
            name='estado',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_retiro',
            name='descripcion_retiro',
            field=models.CharField(default='', max_length=255),
        ),
    ]
